# ******************************************************************************
#
# elective:  a Python configuration loader generator
#
# Copyright 2021 Jeremy A Gray <gray@flyquackswim.com>.
#
# SPDX-License-Identifier: MIT
#
# ******************************************************************************

"""elective configuration functions."""


def _generate_argparse_warranty(conf=None):
    """Generate the ``argparse`` show warranty option."""
    parser_block = """\
    parser.add_argument(
        "--show-warranty",
        nargs=0,
        action=_ShowLicenseAction,
        help="Show warranty information.",
    )
"""

    parser_class = """\
class _ShowWarrantyAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        warranty = \"\"\"\
elective:  a Python configuration loader generator.

Copyright 2021 Jeremy A Gray <gray@flyquackswim.com>.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

\"\"\"
        print(
            "\\n\\n".join(
                list(
                    map(
                        lambda item: "\\n".join(textwrap.wrap(item.strip(), 72)),
                        textwrap.dedent(license).strip().split("\\n\\n"),
                    )
                )
            )
        )

        sys.exit(0)
"""

    return {
        "blocks": [parser_block],
        "classes": [parser_class],
    }


def _generate_argparse_license(conf=None):
    """Generate the ``argparse`` show license option."""
    parser_block = """\
    parser.add_argument(
        "--show-license",
        nargs=0,
        action=_ShowLicenseAction,
        help="Show license information.",
    )
"""

    parser_class = """\
class _ShowLicenseAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        license = \"\"\"\
elective:  a Python configuration loader generator.

Copyright 2021 Jeremy A Gray <gray@flyquackswim.com>.

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

\"\"\"
        print(
            "\\n\\n".join(
                list(
                    map(
                        lambda item: "\\n".join(textwrap.wrap(item.strip(), 72)),
                        textwrap.dedent(license).strip().split("\\n\\n"),
                    )
                )
            )
        )

        sys.exit(0)
"""

    return {
        "blocks": [parser_block],
        "classes": [parser_class],
    }


def generate(conf=None):
    """Generate a configuration loader."""
    module = """\
\"\"\"Configuration module generated by elective.\"\"\"
import argparse
import sys
import textwrap


def _create_argument_parser():
    \"\"\"Create an argparse argument parser.\"\"\"
    parser = argparse.ArgumentParser(
        description=\"\"\"\
This program comes with ABSOLUTELY NO WARRANTY; for details type
``elective --show-warranty``.  This is free software, and you are welcome
to redistribute it under certain conditions; type ``elective
--show-license`` for details.
\"\"\",
    )

"""

    warranty = _generate_argparse_warranty()
    license = _generate_argparse_license()

    module += warranty["blocks"][0]
    module += license["blocks"][0]

    module += """\
    spell_group = parser.add_mutually_exclusive_group()
    spell_group.add_argument(
        "-c",
        "--spell-check",
        dest="spell_check",
        default=None,
        action="store_true",
        help="Spell check the commit.  Default is no spell checking.",
    )
    spell_group.add_argument(
        "-C",
        "--no-spell-check",
        dest="spell_check",
        default=None,
        action="store_false",
        help="Do not spell check the commit.  Default is no spell checking.",
    )

    return parser


"""

    module += warranty["classes"][0]
    module += license["classes"][0]
    module += """\


def load(argv=None):
    \"\"\"Load the configuration.\"\"\"
    args = _create_argument_parser().parse_args(argv)

    return args
"""

    return module
